# Data Wrangling & Visualization

You have just learned the basics of Python programming --- congrats! Now, let's learn how to wrangle and visualize data.

This second part of the course covers two external libraries: `numpy` and `pandas`. Both are essential workhorses of data wrangling with Python.
`numpy` is a library for scientific computing and many other libraries are built on top of this one. `pandas` is a data analysis and manipulation tool and the best choice when working with tabular data. At the end of this lecture we will also introduce and use `matplotlib` for simple plotting.

## Lecture Notes

::: slide-deck
**Part 3: Libraries, Data Frames, Data Wrangling, and Visualization**

::: slides
```{r echo=FALSE}
xfun::embed_file("slides/Lecture_3_Intro_Python.pdf", text = "Slides")
```
:::
:::


## Application Exercise During the Course

:::: application-exercise
**Data Wrangling and Plotting**

Please open Google Colab for this exercise through the following link.
After opening the Google Colab instance, save a copy to your own Google drive.
That's how you will retain your copy with your own code.

::: source
[Exercise Template on Google Colab](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%203%20Data%20Wrangling%20and%20Visualizations/Exercises_Lecture_3.ipynb){target="_blank"}
:::

<!-- Note: Comment the solutions if you don't want to show them. -->
<!-- After the course unit, you can uncomment them -->

<!-- ::: source -->
<!-- [Solution](insert-link-here){target="_blank"}  -->
<!-- ::: -->
:::



## Additional Application Exercises for Self-Study

Excited for more data wrangling and visualization? 
Check out the following additional exercises that let you visualize AirBnB data from Berlin.

:::: application-exercise
**Data Wrangling and Plotting with AirBnB data**


::: source
[Exercise Template on Google Colab](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%203%20Data%20Wrangling%20and%20Visualizations/GroupExercise_Lecture_3.ipynb){target="_blank"} 
:::

<!-- Note: Comment the solutions if you don't want to show them. -->
<!-- After the course unit, you can uncomment them -->

::: solutionlink
[Solution](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%203%20Data%20Wrangling%20and%20Visualizations/Homework_Lecture_3_solutions.ipynb){target="_blank"}
:::
:::

