# Advanced Visualization & Modeling

Two out of three --- done! Now, let's get to the last part of the course.
And maybe the most exciting part: advanced visualization with `seaborn` and some fancy machine learning modeling with `scikit-learn` (we admit, it's just a regression --- but the neural networks or gradient boosting algorithms are just a couple of code lines away).

## Lecture Notes

::: slide-deck
**Part 4: Advanced Visualization and Modeling**

::: slides
```{r echo=FALSE}
xfun::embed_file("slides/Lecture_4_Intro_Python.pdf", text = "Slides")
```
:::
:::


## Application Exercise During the Course

:::: application-exercise
**Visualizing Weather Data and Predicting Apartment Prices**

Please open Google Colab for this exercise through the following link.
After opening the Google Colab instance, save a copy to your own Google drive.
That's how you will retain your copy with your own code.

::: source
[Exercise Template on Google Colab](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%204%20Advanced%20Visualizations/Exercises_Lecture_4.ipynb){target="_blank"}
:::

<!-- Note: Comment the solutions if you don't want to show them. -->
<!-- After the course unit, you can uncomment them -->

<!-- ::: source -->
<!-- [Solution](insert-link-here){target="_blank"}  -->
<!-- ::: -->
:::



## Additional Application Exercises for Self-Study

Excited for more data wrangling and visualization? 
Check out the following additional exercises that let you visualize AirBnB data from Berlin.

:::: application-exercise
**Modeling with AirBnB data**


::: source
[Exercise Template on Google Colab](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%204%20Advanced%20Visualizations/GroupExercise_Lecture_4.ipynb){target="_blank"} 
:::

<!-- Note: Comment the solutions if you don't want to show them. -->
<!-- After the course unit, you can uncomment them -->

::: solutionlink
[Solution](https://colab.research.google.com/github/coding-intro/intro-python-2023-07/blob/main/notebooks/Part%204%20Advanced%20Visualizations/GroupExercise_Lecture_4_Solutions.ipynb){target="_blank"}
:::
:::

